AllCops:
  TargetRubyVersion: 2.1

Metrics/LineLength:
  Max: 99
  Exclude:
    - test/*

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'

Metrics/AbcSize:
  Exclude:
    - test/*

Metrics/ClassLength:
  Exclude:
    - test/*

Metrics/MethodLength:
  Exclude:
    - test/*

Style/Documentation:
  Enabled: false
