language: ruby
cache: bundler
rvm:
  - ruby-2.1
  - ruby-2.2
  - ruby-2.3
  - ruby-2.4
  - jruby-9.1.8.0
jdk:
  - oraclejdk8
env:
  - "JRUBY_OPTS='--dev --debug'"
  - "JRUBY_OPTS='-Xcompile.invokedynamic=true --debug'"
matrix:
  exclude:
    - rvm: ruby-2.1
      jdk: oraclejdk8
      env: "JRUBY_OPTS='-Xcompile.invokedynamic=true --debug'"
    - rvm: ruby-2.2
      jdk: oraclejdk8
      env: "JRUBY_OPTS='-Xcompile.invokedynamic=true --debug'"
    - rvm: ruby-2.3
      jdk: oraclejdk8
      env: "JRUBY_OPTS='-Xcompile.invokedynamic=true --debug'"
    - rvm: ruby-2.4
      jdk: oraclejdk8
      env: "JRUBY_OPTS='-Xcompile.invokedynamic=true --debug'"
  allow_failures:
    - rvm: jruby-9.1.8.0
      jdk: oraclejdk8
      env: "JRUBY_OPTS='-Xcompile.invokedynamic=true --debug'"
before_install:
  - gem update --system
  - gem install bundler -v 1.14.6
before_script:
  - bundle exec danger
