# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#

version: 2

common_steps: &common_steps
  - checkout
  - run: gem update --system
  - restore_cache:
      key: gem-cache-{{ .Branch }}-{{ checksum "Gemfile" }}
  - run:
      name: install dependencies
      command: |
        gem update bundler
        bundle install --jobs=4 --retry=3 --path vendor/bundle
  - save_cache:
      key: gem-cache-{{ .Branch }}-{{ checksum "Gemfile" }}
      paths:
        - vendor/bundle
  - run: bundle exec rake test

jobs:
  ruby-2.7:
    docker:
      - image: cimg/ruby:2.7
    steps:
      *common_steps
  ruby-3.0:
    docker:
      - image: cimg/ruby:3.0
    steps:
      *common_steps
  ruby-3.1:
    docker:
      - image: cimg/ruby:3.1
    steps:
      *common_steps

workflows:
  version: 2
  build:
    jobs:
      - ruby-2.7
      - ruby-3.0
      - ruby-3.1
